import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/app/Component/Navbar";
import { CurrentUserProvider } from "@/app/contexts/CurrentUserContext";

const geistSans = localFont({
  src: "/font/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "/font/GeistVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CurrentUserProvider>
          <Navbar />
          {children}
        </CurrentUserProvider>
      </body>
    </html>
  );
}
